services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - mern_network
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - backend-node-modules:/app/node_modules
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mern_network
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
  backend-node-modules:
  frontend-node-modules: